models/Dialogs.php
<?php

namespace app\models;

use Yii;
use yii\data\ActiveDataProvider;

/**
 * This is the model class for table "dialogs".
 *
 * @property int $id
 * @property int $service_id
 *
 * @property DialogMessages[] $dialogMessages
 * @property Services $service
 * @property UserDialogs[] $userDialogs
 */
class Dialogs extends \yii\db\ActiveRecord {

    /**
     * {@inheritdoc}
     */
    public static function tableName() {
        return 'dialogs';
    }

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
            [['service_id'], 'required'],
            [['service_id'], 'integer'],
            [['service_id'], 'exist', 'targetClass' => Services::className(), 'targetAttribute' => ['service_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'service_id' => 'Service ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDialogMessages() {
        return $this->hasMany(DialogMessages::className(), ['dialog_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getService() {
        return $this->hasOne(Services::className(), ['id' => 'service_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserDialogs() {
        return $this->hasMany(UserDialogs::className(), ['dialog_id' => 'id']);
    }

    public function getMessagesDataProvider() {




        return new ActiveDataProvider(['query' =>
//            DialogMessages::find()->where(['dialog_id' => $this->id])])
            DialogMessages::findBySql("SELECT * FROM (SELECT * FROM `dialog_messages` WHERE dialog_id = {$this->id} ORDER BY id DESC) as base ORDER BY ID ASC"),
                    'pagination'=>[
                        'defaultPageSize'=>DialogMessages::findBySql("SELECT * FROM (SELECT * FROM `dialog_messages` WHERE dialog_id = {$this->id} ORDER BY id DESC) as base ORDER BY ID ASC")->count(),
                    ]
        ]);
    }

}

controllers/DialogsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Dialogs;
use app\models\search\DialogSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\DialogMessages;

/**
 * DialogsController implements the CRUD actions for Dialogs model.
 */
class DialogsController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex() {
        $searchModel = new DialogSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id) {

        $model = $this->findModel($id);
        $new_message = new DialogMessages(['dialog_id' => $model->id, 'owner_id' => Yii::$app->user->id]);
        if ($new_message->load(Yii::$app->request->post()) and $new_message->save()) {
            return $this->refresh();
        }
        Yii::error(print_r($new_message->errors, true));
        return $this->render('view', [
                    'model' => $model,
                    'new_message' => $new_message,
                    'dataProvider' => $model->messagesDataProvider,
        ]);
    }

    public function actionCreate($service_id) {
        $service = Yii::$app->serviceHelper->findModel($service_id);
        if (Yii::$app->getDb()->transaction(function() use ($service) {
                    return Yii::$app->dialogHelper->createNew($service->id, $service->owner_id, Yii::$app->user->id);
                })) {
            return $this->redirect(['/dialogs/view', 'id' => Yii::$app->dialogHelper->top()->id]);
        }
        return $this->goBack();
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id) {
        if (($model = Dialogs::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

controllers/ServicesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Services;
use app\models\search\ServicesSearch;
use app\models\search\ServiceSelfSearch;
use app\models\search\ServiceFavoritesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ServicesController implements the CRUD actions for Services model.
 */
class ServicesController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index'],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['?','@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex() {
        $searchModel = new ServicesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSelf() {
        $searchModel = new ServiceSelfSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('self', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionFavorites() {
        $searchModel = new ServiceFavoritesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('favorites', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate() {
        $model = new Services(['owner_id' => Yii::$app->user->id]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        Yii::error(print_r($model->errors, true));

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id) {
        if (($model = Services::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionToggleFavorite($service_id) {
        return Yii::$app->serviceHelper->toggleFavorite($service_id);
    }

}

views/dialogs/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Dialogs */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="dialogs-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'service_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/dialogs/_message.php
<div class="<?= $model->owner_id === Yii::$app->user->id ? 'text-right' : 'text-left' ?>">
    <?= $model->content ?>
</div>

views/dialogs/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\DialogSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="dialogs-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'service_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/dialogs/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Dialogs */

$this->title = 'Create Dialogs';
$this->params['breadcrumbs'][] = ['label' => 'Dialogs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="dialogs-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/dialogs/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\DialogSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Діалоги';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="dialogs-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'service.name',
                'format' => 'html',
                'value' => function($model) {
                    return Html::a($model->service->name, ['view', 'id' => $model->id]);
                },
            ],
            [
                'label' => 'Електронна пошта',
                'attribute' => 'service.owner.email_address',
            ],
//            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]);
    ?>
    <?php Pjax::end(); ?>
</div>

views/dialogs/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Dialogs */

$this->title = 'Update Dialogs: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Dialogs', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="dialogs-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/dialogs/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ListView;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model app\models\Dialogs */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Діалоги', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="dialogs-view">

    <h3><?= Html::encode("Діалог з {$model->service->owner->email_address} / Послуга (") . Html::a($model->service->name, ['services/view', 'id' => $model->service_id]) . ")" ?></h3>

</div>
<?php Pjax::begin(['id' => 'chat']) ?>
<?= ListView::widget(['dataProvider' => $dataProvider, 'itemView' => '_message', 'layout' => '{items}{pager}']) ?>
<?php Pjax::end() ?>
<?php $form = ActiveForm::begin(); ?>
<?= $form->field($new_message, 'content')->textarea(['rows' => 6])->label(false) ?>
<?= Html::submitButton('Відправити', ['class' => 'btn btn-success']) ?>
<?php ActiveForm::end(); ?>
<script>
    setTimeout(function () {
        $.pjax.reload({container: '#chat', async: false});
    }
    , 5000)
</script>