models/Services.php
<?php

namespace app\models;

use Yii;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "services".
 *
 * @property int $id
 * @property string $name
 * @property int $category_id
 * @property int $owner_id
 * @property string $description
 * @property string $price
 * @property string $created_at
 * @property string $updated_at
 * @property int $city_id
 * @property int $is_active
 * @property string $preview_image_name
 */
class Services extends \yii\db\ActiveRecord {

    public static function tableName() {
        return 'services';
    }

    public function behaviors() {
        return [
            'timestamps' => [
                'class' => TimestampBehavior::className(),
                'value' => new Expression('NOW()'),
            ]
        ];
    }

    public function rules() {
        return [
            [['name', 'category_id', 'owner_id', 'description', 'price', 'city_id', 'is_active'], 'required'],
            [['category_id', 'owner_id', 'city_id', 'is_active'], 'integer'],
            [['description'], 'string'],
            [['price'], 'number'],
            [['created_at', 'updated_at'], 'safe'],
            [['name'], 'string', 'max' => 255],
            [['preview_image_name'], 'string', 'max' => 64],
        ];
    }

    public function attributeLabels() {
        return [
            'id' => 'ID',
            'name' => 'Назва',
            'category_id' => 'Категорія',
            'owner_id' => 'Owner ID',
            'description' => 'Інформація',
            'price' => 'Ціна',
            'created_at' => 'Опубліковано',
            'updated_at' => 'Updated At',
            'city_id' => 'Місто',
            'is_active' => 'Активно',
        ];
    }

    public function getCity() {
        return $this->hasOne(Cities::className(), ['id' => 'city_id']);
    }

    public function getOwner() {
        return $this->hasOne(Users::className(), ['id' => 'owner_id']);
    }

    public function getCategory() {
        return $this->hasOne(Categories::className(), ['id' => 'category_id']);
    }

    public function getFavorites() {
        return $this->hasMany(FavoriteServices::className(), ['service_id' => 'id']);
    }

}

controllers/DialogsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Dialogs;
use app\models\search\DialogSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\DialogMessages;

/**
 * DialogsController implements the CRUD actions for Dialogs model.
 */
class DialogsController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex() {
        $searchModel = new DialogSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id) {

        $model = $this->findModel($id);
        $new_message = new DialogMessages(['dialog_id' => $model->id, 'owner_id' => Yii::$app->user->id]);
        if ($new_message->load(Yii::$app->request->post()) and $new_message->save()) {
            return $this->refresh();
        }
        Yii::error(print_r($new_message->errors, true));
        return $this->render('view', [
                    'model' => $model,
                    'new_message' => $new_message,
                    'dataProvider' => $model->messagesDataProvider,
        ]);
    }

    public function actionCreate($service_id) {
        $service = Yii::$app->serviceHelper->findModel($service_id);
        if (Yii::$app->getDb()->transaction(function() use ($service) {
                    return Yii::$app->dialogHelper->createNew($service->id, $service->owner_id, Yii::$app->user->id);
                })) {
            return $this->redirect(['/dialogs/view', 'id' => Yii::$app->dialogHelper->top()->id]);
        }
        return $this->goBack();
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id) {
        if (($model = Dialogs::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

controllers/ServicesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Services;
use app\models\search\ServicesSearch;
use app\models\search\ServiceSelfSearch;
use app\models\search\ServiceFavoritesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ServicesController implements the CRUD actions for Services model.
 */
class ServicesController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index'],
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['?','@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex() {
        $searchModel = new ServicesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSelf() {
        $searchModel = new ServiceSelfSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('self', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionFavorites() {
        $searchModel = new ServiceFavoritesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('favorites', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate() {
        $model = new Services(['owner_id' => Yii::$app->user->id]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        Yii::error(print_r($model->errors, true));

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id) {
        if (($model = Services::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionToggleFavorite($service_id) {
        return Yii::$app->serviceHelper->toggleFavorite($service_id);
    }

}

views/services/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\tinymce\TinyMce;


/* @var $this yii\web\View */
/* @var $model app\models\Services */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="services-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'price')->textInput(['maxlength' => true]) ?>


    <?= $form->field($model, 'category_id')->dropDownList(Yii::$app->categoryHelper->getList()) ?>
    <?= $form->field($model, 'city_id')->dropDownList(Yii::$app->cityHelper->getList()) ?>

    <?=
    $form->field($model, 'description')->widget(TinyMce::className(), [
        'options' => ['rows' => 6],
        'language' => 'ru',
        'clientOptions' => [
            'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
        ]
    ]);
    ?>
    <?= $form->field($model, 'is_active')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/services/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\ServicesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="services-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'category_id') ?>

    <?= $form->field($model, 'owner_id') ?>

    <?= $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'city_id') ?>

    <?php // echo $form->field($model, 'is_active') ?>

    <?php // echo $form->field($model, 'preview_image_name') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/services/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Services */

$this->title = 'Create Services';
$this->params['breadcrumbs'][] = ['label' => 'Services', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="services-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/services/favorites.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use app\widgets\ServicesWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\ServicesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Закладки';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="services-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= ServicesWidget::widget() ?>
    <?php Pjax::begin(['id' => 'favorites']); ?>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'name',
                'format' => 'html',
                'value' => function($model) {
                    return Html::a($model->name, ['view', 'id' => $model->id]);
                }
            ],
            [
                'attribute' => 'category_id',
                'value' => 'category.name',
                'filter' => Yii::$app->categoryHelper->getList(),
            ],
            'price:integer',
            [
                'attribute' => 'city_id',
                'value' => 'city.name',
                'filter' => Yii::$app->cityHelper->getList(),
            ],
            ['class' => 'yii\grid\ActionColumn',
                'template' => '{toggle-favorite}',
                'buttons' => [
                    'toggle-favorite' => function($uri, $model) {
                        return Html::a('', ['services/toggle-favorite', 'service_id' => $model->id], ['class' => Yii::$app->serviceHelper->isFavorite($model->id) ? 'glyphicon glyphicon-star' : 'glyphicon glyphicon-star-empty', 'onclick' => 'toggle_favorite(event)', 'data-id' => $model->id]);
                    }
                ]
            ],
        ],
    ]);
    ?>


    <?php Pjax::end(); ?>
</div>
<script>
    function toggle_favorite(event) {
        event.preventDefault();
        $.ajax({
            url: '/services/toggle-favorite',
            data: {service_id: event.target.dataset.id},
            success: function () {
                $.pjax.reload({container: '#favorites'});
            }
        });
    }

</script>

views/services/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use app\widgets\ServicesWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\ServicesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Послуги';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="services-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= ServicesWidget::widget() ?>
    <?php Pjax::begin(['id' => 'index']); ?>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'name',
                'format' => 'html',
                'value' => function($model) {
                    return Html::a($model->name, ['view', 'id' => $model->id]);
                }
            ],
            [
                'attribute' => 'category_id',
                'value' => 'category.name',
                'filter' => Yii::$app->categoryHelper->getList(),
            ],
            'price:integer',
            [
                'attribute' => 'city_id',
                'value' => 'city.name',
                'filter' => Yii::$app->cityHelper->getList(),
            ],
            ['class' => 'yii\grid\ActionColumn',
                'template' => '{send-message}{toggle-favorite}',
                'buttons' => [
                    'send-message' => function($uri, $model) {
                        if (!($dialog = Yii::$app->dialogHelper->find(Yii::$app->user->id, $model->id))) {
                            return Html::a('', ['dialogs/create', 'service_id' => $model->id], ['class' => 'glyphicon glyphicon-envelope']);
                        } else {
                            return Html::a('', ['dialogs/view', 'id' => $dialog->id], ['class' => 'glyphicon glyphicon-envelope']);
                        }
                    },
                    'toggle-favorite' => function($uri, $model) {
                        return Html::a('', ['services/toggle-favorite', 'service_id' => $model->id], ['class' => Yii::$app->serviceHelper->isFavorite($model->id) ? 'glyphicon glyphicon-star' : 'glyphicon glyphicon-star-empty', 'onclick' => 'toggle_favorite(event)', 'data-id' => $model->id]);
                    }
                ]
            ],
        ],
    ]);
    ?>


    <?php Pjax::end(); ?>
</div>

<script>
    function toggle_favorite(event) {
        event.preventDefault();
        $.ajax({
            url: '/services/toggle-favorite',
            data: {service_id: event.target.dataset.id},
            success: function () {
                $.pjax.reload({container: '#index'});
            }
        });
    }

</script>

views/services/self.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use app\widgets\ServicesWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\ServicesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Мої послуги';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="services-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= ServicesWidget::widget() ?>
    <?php Pjax::begin(); ?>

    <p>
        <?= Html::a('Додати', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'name',
            [
                'attribute' => 'category_id',
                'value' => 'category.name',
                'filter' => Yii::$app->categoryHelper->getList(),
            ],
            'price:integer',
            [
                'attribute' => 'city_id',
                'value' => 'city.name',
                'filter' => Yii::$app->cityHelper->getList(),
            ],
            'is_active:boolean',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]);
    ?>


    <?php Pjax::end(); ?>
</div>

views/services/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Services */

$this->title = 'Update Services: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Services', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="services-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/services/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Services */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Services', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="services-view">


    <p>
        <?php if (Yii::$app->user->id === $model->owner->id): ?>
            <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
            <?=
            Html::a('Delete', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Are you sure you want to delete this item?',
                    'method' => 'post',
                ],
            ])
            ?>
    <?php endif; ?>
    </p>

    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            'category.name',
            'owner.name',
            'description:html',
            'price:integer',
            'created_at:date',
            'city.name',
            'is_active:boolean',
        ],
    ])
    ?>

</div>